### ISSUE TITLE
Does not build on GCC 4.8.5 due to incomplete C++11 support.

### ISSUE THREAD

**Issue by mloskot** [nanodbc/nanodbc#121]
_From @saur0n on September 4, 2016 8:6_

Library does not build under GCC 4.8.5:

```
src/Nanodbc.cpp:3027:70: error: no matching function for call to ‘find(std::initializer_list<unsigned char*>&, const std::initializer_list<unsigned char* const>&, char)
```

_Copied from original issue: lexicalunit/nanodbc#207_

**Comment by mloskot** [comment]
_From @lexicalunit on September 5, 2016 1:22_

It seems like GCC 4.5 doesn't support a lot of the features nanodbc is built on. For example: `nullptr`, `noexcept`, `std::move()`, thread local storage (upcoming PR), and there may be others. It may be possible to work around these issues in some way but I'm not personally interested in doing that work. I'll leave this ticket open as documentation of this issue and as an invitation to anyone who wishes to submit a PR to resolve it.

**Comment by mloskot** [comment]
I think _nanodbc requires GCC 5_ now.

On Travis CI, we use GCC 5.4

On AppVeyor, MinGW w/ GCC 5.3, while MinGW w/ GCC 4.9.3 build [fails](https://ci.appveyor.com/project/lexicalunit/nanodbc/branch/master/job/ghyouv3gdvlko7i5) due to:

```
codecvt: No such file or directory
 #include <codecvt>
```

**Comment by mloskot** [comment]
_From @saur0n on September 5, 2016 16:45_

> It seems like GCC 4.5 doesn't support a lot of the features nanodbc is built on.

When I commented out `find_drivers()`, it compiles successfully. I use `-DNANODBC_USE_BOOST_CONVERT` instead of `<codecvt>`.

**Comment by mloskot** [comment]
I assume it's been fixed now by #208
